from pptx import Presentation
from src.safwanbuddy.core import logger

class PowerPointGenerator:
    def create_presentation(self, title: str, slides_content: list, save_path: str):
        """
        slides_content: list of dicts like {"title": "...", "content": ["...", "..."]}
        """
        prs = Presentation()
        
        # Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        title_shape.text = title
        subtitle_shape.text = "Generated by SafwanBuddy"

        for item in slides_content:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]

            title_shape.text = item.get("title", "")
            tf = body_shape.text_frame
            for bullet in item.get("content", []):
                p = tf.add_paragraph()
                p.text = bullet
                p.level = 0

        prs.save(save_path)
        logger.info(f"PowerPoint presentation saved to {save_path}")

powerpoint_generator = PowerPointGenerator()
