from docx import Document
from docx.shared import Inches
from src.safwanbuddy.core import logger
import os

class WordGenerator:
    def __init__(self):
        self.output_dir = "output/documents"
        os.makedirs(self.output_dir, exist_ok=True)

    def create_document(self, title: str, content: list, filename: str = "document.docx"):
        """
        Creates a Word document with professional styling.
        content is a list of dicts: [{"type": "paragraph", "text": "..."}, {"type": "heading", "level": 1, "text": "..."}]
        """
        try:
            doc = Document()
            
            # Header
            section = doc.sections[0]
            header = section.header
            header_para = header.paragraphs[0]
            header_para.text = "SafwanBuddy Ultimate++ Intelligence Report"
            header_para.alignment = 1 # Center
            
            doc.add_heading(title, 0)

            for item in content:
                c_type = item.get("type")
                text = item.get("text", "")
                
                if c_type == "paragraph":
                    p = doc.add_paragraph(text)
                elif c_type == "heading":
                    doc.add_heading(text, level=item.get("level", 1))
                elif c_type == "bullet":
                    doc.add_paragraph(text, style='List Bullet')
                elif c_type == "numbered":
                    doc.add_paragraph(text, style='List Number')
                elif c_type == "table":
                    rows = item.get("rows", [])
                    if rows:
                        table = doc.add_table(rows=len(rows), cols=len(rows[0]))
                        table.style = 'Light Grid Accent 1'
                        for i, row in enumerate(rows):
                            for j, cell_text in enumerate(row):
                                table.cell(i, j).text = str(cell_text)

            # Footer
            footer = section.footer
            footer_para = footer.paragraphs[0]
            footer_para.text = "Generated by SafwanBuddy Expert Mode v7.0"
            footer_para.alignment = 2 # Right

            path = os.path.join(self.output_dir, filename)
            doc.save(path)
            logger.info(f"Word document saved to {path}")
            return path
        except Exception as e:
            logger.error(f"Error creating Word document: {e}")
            return None

word_generator = WordGenerator()
