# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller specification file for SafwaanBuddy Ultimate++ v7.0
This file defines how to package the application into a standalone executable.
"""

import sys
from pathlib import Path

block_cipher = None

# Define the main entry point
a = Analysis(
    ['run_safwaanbuddy.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config', 'config'),
        ('data/profiles', 'data/profiles'),
        ('data/templates', 'data/templates'),
        ('src/safwaanbuddy', 'safwaanbuddy'),
        ('.env.example', '.'),
        ('README.md', '.'),
        ('LICENSE', '.'),
    ],
    hiddenimports=[
        'safwaanbuddy',
        'safwaanbuddy.core',
        'safwaanbuddy.core.events',
        'safwaanbuddy.core.config',
        'safwaanbuddy.core.logger',
        'safwaanbuddy.voice',
        'safwaanbuddy.voice.speech_recognition',
        'safwaanbuddy.voice.text_to_speech',
        'safwaanbuddy.voice.command_processor',
        'safwaanbuddy.voice.language_manager',
        'safwaanbuddy.automation',
        'safwaanbuddy.automation.click_system',
        'safwaanbuddy.automation.type_system',
        'safwaanbuddy.automation.form_filler',
        'safwaanbuddy.automation.workflow_engine',
        'safwaanbuddy.vision',
        'safwaanbuddy.vision.screen_capture',
        'safwaanbuddy.vision.ocr_engine',
        'safwaanbuddy.vision.element_detector',
        'safwaanbuddy.web',
        'safwaanbuddy.web.browser_controller',
        'safwaanbuddy.web.search_engine',
        'safwaanbuddy.web.web_scraper',
        'safwaanbuddy.documents',
        'safwaanbuddy.documents.word_generator',
        'safwaanbuddy.documents.excel_generator',
        'safwaanbuddy.documents.pdf_generator',
        'safwaanbuddy.documents.template_manager',
        'safwaanbuddy.profiles',
        'safwaanbuddy.profiles.profile_manager',
        'safwaanbuddy.profiles.form_profiles',
        'safwaanbuddy.profiles.preferences',
        'safwaanbuddy.plugins',
        'safwaanbuddy.plugins.plugin_loader',
        'safwaanbuddy.plugins.plugin_calculator',
        'safwaanbuddy.plugins.plugin_notes',
        'safwaanbuddy.plugins.plugin_file_ops',
        'safwaanbuddy.gui',
        'safwaanbuddy.gui.main_window',
        'safwaanbuddy.utils',
        'safwaanbuddy.utils.helpers',
        'safwaanbuddy.utils.monitoring',
        'safwaanbuddy.utils.alerts',
        'safwaanbuddy.social',
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtWebEngineWidgets',
        'yaml',
        'vosk',
        'pyttsx3',
        'numpy',
        'PIL',
        'cv2',
        'selenium',
        'bs4',
        'docx',
        'openpyxl',
        'reportlab',
        'pytesseract',
        'mss',
        'pyautogui',
        'keyboard',
        'mouse',
        'sounddevice',
        'soundfile',
        'cryptography',
        'psutil',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'pandas',
        'scipy.sparse.csgraph._validation',
        'tkinter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SafwaanBuddy',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # Set to False for GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico' if Path('assets/icon.ico').exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SafwaanBuddy',
)
