from src.safwanbuddy.core.events import event_bus
from src.safwanbuddy.core.logging import logger
from src.safwanbuddy.automation.click_system import click_system
from src.safwanbuddy.automation.type_system import type_system
from src.safwanbuddy.automation.workflow_engine import workflow_engine
from src.safwanbuddy.automation.form_filler import form_filler
from src.safwanbuddy.social.unified_interface import social_integrator
from src.safwanbuddy.web.browser_controller import browser_controller
from src.safwanbuddy.web.search_engine import search_engine
from src.safwanbuddy.documents.word_generator import word_generator
from src.safwanbuddy.core.config import config_manager
from src.safwanbuddy.profiles.profile_manager import profile_manager
from src.safwanbuddy.voice.speech_recognition import VoiceRecognizer
import threading

class SafwanBuddyOrchestrator:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(SafwanBuddyOrchestrator, cls).__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self):
        if self._initialized:
            return
        self._initialized = True
        self.subsystems = {}
        self.voice_recognizer = VoiceRecognizer()
        self._setup_event_handlers()

    def _setup_event_handlers(self):
        event_bus.subscribe("automation_request", self._handle_automation)
        event_bus.subscribe("social_request", self._handle_social)
        event_bus.subscribe("document_request", self._handle_document)

    def start(self):
        logger.info("Orchestrator starting subsystems...")
        # Start voice recognition in a separate thread
        voice_thread = threading.Thread(target=self.voice_recognizer.start_listening, daemon=True)
        voice_thread.start()
        logger.info("Voice recognition started.")
        return True

    def _handle_automation(self, data):
        action = data.get("action")
        logger.info(f"Orchestrator handling automation: {action}")
        event_bus.emit("system_log", f"Action: {action}")
        if action == "open_browser":
            browser_controller.launch()
        elif action == "search":
            search_engine.search(data.get("query"))
        elif action == "type_profile":
            type_system.type_profile_info(data.get("field"))
        elif action == "click_text":
            click_system.click_text(data.get("text"))
        elif action == "record_workflow":
            workflow_engine.start_recording()
        elif action == "stop_recording":
            workflow_engine.stop_recording("last_recorded")
        elif action == "run_workflow":
            # This would need a path, but we'll use a mock for now
            logger.info(f"Running workflow: {data.get('name')}")
        elif action == "fill_form":
            profile_id = config_manager.active_profile or "default"
            profile = profile_manager.load_profile(profile_id)
            # Guided form filling logic would go here
            logger.info("Starting form filling...")

    def _handle_social(self, data):
        action = data.get("action")
        logger.info(f"Orchestrator handling social: {action}")
        event_bus.emit("system_log", f"Social: {action}")
        if action == "call":
            social_integrator.initiate_call(data.get("name"), message_to_deliver="Hello, this is SafwanBuddy.")

    def _handle_document(self, data):
        action = data.get("action")
        logger.info(f"Orchestrator handling document: {action}")
        event_bus.emit("system_log", f"Document: {action}")
        if action == "generate_report":
            word_generator.create_document("Report", [{"type": "paragraph", "text": "Generated by SafwanBuddy"}], "report.docx")

    def stop(self):
        logger.info("Orchestrator shutting down...")
        browser_controller.close()
        return True

orchestrator = SafwanBuddyOrchestrator()
